[package]
name = "firefly"
version = "0.1.0"
edition = "2021"

[dependencies]
pin-project-lite = "0.2.9"
thingbuf = "0.1.3"

[dev-dependencies]
criterion = "0.3.5"
crossbeam = "0.8.1"
flume = "0.10.13"

[[bench]]
name = "mpsc"
harness = false
